name: keep tests results history

on: push

permissions:
  contents: write

jobs:
  chrome-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with Cypress tests
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Checkout external repository (Slawek's localstack)
        uses: actions/checkout@v4
        with:
          repository: "slawekradzyminski/awesome-localstack"
          path: "awesome-localstack"
      - name: Run Docker Compose
        run: |
          cd awesome-localstack
          chmod +x run-docker-compose-ci.sh
          ./run-docker-compose-ci.sh
      - name: Install chrome
        uses: browser-actions/setup-chrome@v1
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: |
          npx cypress run \
            --browser chrome \
            --env "login=${{ secrets.USERNAME }},password=${{ secrets.PASSWORD }}" \
            --record \
            --key ${{ secrets.CYPRESS_RECORD_KEY }}
      - name: Save screenshots on failure
        uses: actions/upload-artifact@v4 
        if: failure()
        with:
          name: cypress-screenshots-chrome
          path: cypress/screenshots
          if-no-files-found: ignore
      
      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages # branch name
          path: gh-pages-dir # checkout path

      - name: Allure Report Action
        uses: mgrybyk-org/allure-report-branch-action@v1
        if: always()
        continue-on-error: true
        id: allure # used in comment to PR
        with:
          report_id: 'self-test'
          gh_pages: 'gh-pages-dir'
          report_dir: 'allure-results'
      
      - name: Git Commit and Push Action
        uses: mgrybyk-org/git-commit-pull-push-action@v1
        if: always()
        with:
            repository: gh-pages-dir
            branch: gh-pages
            pull_args: --rebase -X ours

      # - name: Build test report
      #   uses: simple-elf/allure-report-action@v1.7
      #   if: always()
      #   with:
      #     gh_pages: gh-pages
      #     allure_history: allure-history
      #     allure_results: allure-results

      # - name: Publish test report
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: always()
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_branch: gh-pages
      #     publish_dir: allure-history